// Code generated by go-swagger; DO NOT EDIT.

/*
Package serve Account
This is the Account Microservice, responsible for managing accounts and their balances in Modern Bank.


    Schemes:
      http
    Host: account
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package serve
