apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}-{{ .Values.microservice.version }}
  labels:
    app: {{ .Values.microservice.name }}
    version: {{ .Values.microservice.version }}
spec:
  replicas: {{ .Values.microservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
      version: {{ .Values.microservice.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice.name }}
        version: {{ .Values.microservice.version }}
    spec:
      serviceAccountName: {{ .Values.microservice.name }}
      containers:
        - name: {{ .Values.microservice.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.microservice.args }}
          args: {{ .Values.microservice.args }}
          {{- else }}
          args: ["--port", "{{ .Values.microservice.port }}", "--version", "{{ .Values.microservice.version }}"]
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.microservice.port }}
