// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListTransactionsReceivedParams creates a new ListTransactionsReceivedParams object
// with the default values initialized.
func NewListTransactionsReceivedParams() *ListTransactionsReceivedParams {
	var ()
	return &ListTransactionsReceivedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListTransactionsReceivedParamsWithTimeout creates a new ListTransactionsReceivedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListTransactionsReceivedParamsWithTimeout(timeout time.Duration) *ListTransactionsReceivedParams {
	var ()
	return &ListTransactionsReceivedParams{

		timeout: timeout,
	}
}

// NewListTransactionsReceivedParamsWithContext creates a new ListTransactionsReceivedParams object
// with the default values initialized, and the ability to set a context for a request
func NewListTransactionsReceivedParamsWithContext(ctx context.Context) *ListTransactionsReceivedParams {
	var ()
	return &ListTransactionsReceivedParams{

		Context: ctx,
	}
}

// NewListTransactionsReceivedParamsWithHTTPClient creates a new ListTransactionsReceivedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListTransactionsReceivedParamsWithHTTPClient(client *http.Client) *ListTransactionsReceivedParams {
	var ()
	return &ListTransactionsReceivedParams{
		HTTPClient: client,
	}
}

/*ListTransactionsReceivedParams contains all the parameters to send to the API endpoint
for the list transactions received operation typically these are written to a http.Request
*/
type ListTransactionsReceivedParams struct {

	/*Receiver
	  Account number that received the transactions

	*/
	Receiver int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list transactions received params
func (o *ListTransactionsReceivedParams) WithTimeout(timeout time.Duration) *ListTransactionsReceivedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list transactions received params
func (o *ListTransactionsReceivedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list transactions received params
func (o *ListTransactionsReceivedParams) WithContext(ctx context.Context) *ListTransactionsReceivedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list transactions received params
func (o *ListTransactionsReceivedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list transactions received params
func (o *ListTransactionsReceivedParams) WithHTTPClient(client *http.Client) *ListTransactionsReceivedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list transactions received params
func (o *ListTransactionsReceivedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReceiver adds the receiver to the list transactions received params
func (o *ListTransactionsReceivedParams) WithReceiver(receiver int64) *ListTransactionsReceivedParams {
	o.SetReceiver(receiver)
	return o
}

// SetReceiver adds the receiver to the list transactions received params
func (o *ListTransactionsReceivedParams) SetReceiver(receiver int64) {
	o.Receiver = receiver
}

// WriteToRequest writes these params to a swagger request
func (o *ListTransactionsReceivedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param receiver
	if err := r.SetPathParam("receiver", swag.FormatInt64(o.Receiver)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
