// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/transaction-log/pkg/model"
)

// NewMakeTransactionParams creates a new MakeTransactionParams object
// with the default values initialized.
func NewMakeTransactionParams() *MakeTransactionParams {
	var ()
	return &MakeTransactionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMakeTransactionParamsWithTimeout creates a new MakeTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMakeTransactionParamsWithTimeout(timeout time.Duration) *MakeTransactionParams {
	var ()
	return &MakeTransactionParams{

		timeout: timeout,
	}
}

// NewMakeTransactionParamsWithContext creates a new MakeTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewMakeTransactionParamsWithContext(ctx context.Context) *MakeTransactionParams {
	var ()
	return &MakeTransactionParams{

		Context: ctx,
	}
}

// NewMakeTransactionParamsWithHTTPClient creates a new MakeTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMakeTransactionParamsWithHTTPClient(client *http.Client) *MakeTransactionParams {
	var ()
	return &MakeTransactionParams{
		HTTPClient: client,
	}
}

/*MakeTransactionParams contains all the parameters to send to the API endpoint
for the make transaction operation typically these are written to a http.Request
*/
type MakeTransactionParams struct {

	/*Body
	  Transaction to make

	*/
	Body *model.Newtransaction

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the make transaction params
func (o *MakeTransactionParams) WithTimeout(timeout time.Duration) *MakeTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the make transaction params
func (o *MakeTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the make transaction params
func (o *MakeTransactionParams) WithContext(ctx context.Context) *MakeTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the make transaction params
func (o *MakeTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the make transaction params
func (o *MakeTransactionParams) WithHTTPClient(client *http.Client) *MakeTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the make transaction params
func (o *MakeTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the make transaction params
func (o *MakeTransactionParams) WithBody(body *model.Newtransaction) *MakeTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the make transaction params
func (o *MakeTransactionParams) SetBody(body *model.Newtransaction) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MakeTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
