// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/transaction-log/pkg/model"
)

// MakeTransactionReader is a Reader for the MakeTransaction structure.
type MakeTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MakeTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewMakeTransactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewMakeTransactionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMakeTransactionCreated creates a MakeTransactionCreated with default headers values
func NewMakeTransactionCreated() *MakeTransactionCreated {
	return &MakeTransactionCreated{}
}

/*MakeTransactionCreated handles this case with default header values.

Created
*/
type MakeTransactionCreated struct {
	Payload *model.Transaction
}

func (o *MakeTransactionCreated) Error() string {
	return fmt.Sprintf("[POST /transactions][%d] makeTransactionCreated  %+v", 201, o.Payload)
}

func (o *MakeTransactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Transaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakeTransactionInternalServerError creates a MakeTransactionInternalServerError with default headers values
func NewMakeTransactionInternalServerError() *MakeTransactionInternalServerError {
	return &MakeTransactionInternalServerError{}
}

/*MakeTransactionInternalServerError handles this case with default header values.

Internal server error
*/
type MakeTransactionInternalServerError struct {
}

func (o *MakeTransactionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /transactions][%d] makeTransactionInternalServerError ", 500)
}

func (o *MakeTransactionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
