// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new transactions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for transactions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateTransaction sends money from one account to another

Sends money from one account to another
*/
func (a *Client) CreateTransaction(params *CreateTransactionParams) (*CreateTransactionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateTransactionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateTransaction",
		Method:             "POST",
		PathPattern:        "/transactions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateTransactionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateTransactionCreated), nil

}

/*
GetTransactionReceived gets a specific transaction received by a given account

Get a specific transaction received by a given account
*/
func (a *Client) GetTransactionReceived(params *GetTransactionReceivedParams) (*GetTransactionReceivedOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTransactionReceivedParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTransactionReceived",
		Method:             "GET",
		PathPattern:        "/account/{receiver}/received/{transaction}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTransactionReceivedReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTransactionReceivedOK), nil

}

/*
GetTransactionSent gets a specific transaction sent from a given account

Get a specific transaction sent from a given account
*/
func (a *Client) GetTransactionSent(params *GetTransactionSentParams) (*GetTransactionSentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTransactionSentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTransactionSent",
		Method:             "GET",
		PathPattern:        "/account/{sender}/sent/{transaction}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTransactionSentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTransactionSentOK), nil

}

/*
ListTransactionsReceived lists all transactions sent to a given account

Lists all transactions sent to a given account
*/
func (a *Client) ListTransactionsReceived(params *ListTransactionsReceivedParams) (*ListTransactionsReceivedOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTransactionsReceivedParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listTransactionsReceived",
		Method:             "GET",
		PathPattern:        "/account/{receiver}/received",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListTransactionsReceivedReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListTransactionsReceivedOK), nil

}

/*
ListTransactionsSent lists all transactions sent from a given account

Lists all transactions sent from a given account
*/
func (a *Client) ListTransactionsSent(params *ListTransactionsSentParams) (*ListTransactionsSentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTransactionsSentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listTransactionsSent",
		Method:             "GET",
		PathPattern:        "/account/{sender}/sent",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListTransactionsSentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListTransactionsSentOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
