// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTransactionReceivedParams creates a new GetTransactionReceivedParams object
// no default values defined in spec.
func NewGetTransactionReceivedParams() GetTransactionReceivedParams {

	return GetTransactionReceivedParams{}
}

// GetTransactionReceivedParams contains all the bound params for the get transaction received operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTransactionReceived
type GetTransactionReceivedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Account number that received the transactions
	  Required: true
	  In: path
	*/
	Receiver int64
	/*Transaction ID
	  Required: true
	  In: path
	*/
	Transaction int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTransactionReceivedParams() beforehand.
func (o *GetTransactionReceivedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rReceiver, rhkReceiver, _ := route.Params.GetOK("receiver")
	if err := o.bindReceiver(rReceiver, rhkReceiver, route.Formats); err != nil {
		res = append(res, err)
	}

	rTransaction, rhkTransaction, _ := route.Params.GetOK("transaction")
	if err := o.bindTransaction(rTransaction, rhkTransaction, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReceiver binds and validates parameter Receiver from path.
func (o *GetTransactionReceivedParams) bindReceiver(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("receiver", "path", "int64", raw)
	}
	o.Receiver = value

	return nil
}

// bindTransaction binds and validates parameter Transaction from path.
func (o *GetTransactionReceivedParams) bindTransaction(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("transaction", "path", "int64", raw)
	}
	o.Transaction = value

	return nil
}
