// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	flag "github.com/spf13/pflag"
	"github.com/tetrateio/training/samples/modernbank/microservices/transaction-log/pkg/serve"
	"github.com/tetrateio/training/samples/modernbank/microservices/transaction-log/pkg/serve/restapi"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(serve.SwaggerJSON, serve.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *serve.Server // make sure init is called

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  transaction-log-server [OPTIONS]\n\n")

		title := "Transaction Log"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "This is the Transaction Log Microservice, an immutable append-only Transaction Log in Modern Bank."
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}
	// parse the CLI flags
	flag.Parse()

	api := restapi.NewTransactionLogAPI(swaggerSpec)
	// get server with flag values filled out
	server = serve.NewServer(api)

	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
