// Code generated by go-swagger; DO NOT EDIT.

/*
Package serve Transaction
This is the Transaction Processing Microservice, ensuring transactions are processed in Modern Bank.


    Schemes:
      http
    Host: transaction
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package serve
