// Code generated by go-swagger; DO NOT EDIT.

package payment_processing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/payment-processing/pkg/model"
)

// MakePaymentReader is a Reader for the MakePayment structure.
type MakePaymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MakePaymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewMakePaymentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewMakePaymentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMakePaymentCreated creates a MakePaymentCreated with default headers values
func NewMakePaymentCreated() *MakePaymentCreated {
	return &MakePaymentCreated{}
}

/*MakePaymentCreated handles this case with default header values.

Created
*/
type MakePaymentCreated struct {
	Payload *model.Payment
}

func (o *MakePaymentCreated) Error() string {
	return fmt.Sprintf("[POST /payment][%d] makePaymentCreated  %+v", 201, o.Payload)
}

func (o *MakePaymentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Payment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakePaymentInternalServerError creates a MakePaymentInternalServerError with default headers values
func NewMakePaymentInternalServerError() *MakePaymentInternalServerError {
	return &MakePaymentInternalServerError{}
}

/*MakePaymentInternalServerError handles this case with default header values.

Internal server error
*/
type MakePaymentInternalServerError struct {
}

func (o *MakePaymentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /payment][%d] makePaymentInternalServerError ", 500)
}

func (o *MakePaymentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
