// Code generated by go-swagger; DO NOT EDIT.

package payment_processing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/payment-processing/pkg/model"
)

// NewMakePaymentParams creates a new MakePaymentParams object
// with the default values initialized.
func NewMakePaymentParams() *MakePaymentParams {
	var ()
	return &MakePaymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMakePaymentParamsWithTimeout creates a new MakePaymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMakePaymentParamsWithTimeout(timeout time.Duration) *MakePaymentParams {
	var ()
	return &MakePaymentParams{

		timeout: timeout,
	}
}

// NewMakePaymentParamsWithContext creates a new MakePaymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewMakePaymentParamsWithContext(ctx context.Context) *MakePaymentParams {
	var ()
	return &MakePaymentParams{

		Context: ctx,
	}
}

// NewMakePaymentParamsWithHTTPClient creates a new MakePaymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMakePaymentParamsWithHTTPClient(client *http.Client) *MakePaymentParams {
	var ()
	return &MakePaymentParams{
		HTTPClient: client,
	}
}

/*MakePaymentParams contains all the parameters to send to the API endpoint
for the make payment operation typically these are written to a http.Request
*/
type MakePaymentParams struct {

	/*Body
	  Payment to make

	*/
	Body *model.Payment

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the make payment params
func (o *MakePaymentParams) WithTimeout(timeout time.Duration) *MakePaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the make payment params
func (o *MakePaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the make payment params
func (o *MakePaymentParams) WithContext(ctx context.Context) *MakePaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the make payment params
func (o *MakePaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the make payment params
func (o *MakePaymentParams) WithHTTPClient(client *http.Client) *MakePaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the make payment params
func (o *MakePaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the make payment params
func (o *MakePaymentParams) WithBody(body *model.Payment) *MakePaymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the make payment params
func (o *MakePaymentParams) SetBody(body *model.Payment) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MakePaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
