// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUserOKCode is the HTTP code returned for type DeleteUserOK
const DeleteUserOKCode int = 200

/*DeleteUserOK Success!

swagger:response deleteUserOK
*/
type DeleteUserOK struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteUserOK creates DeleteUserOK with default headers values
func NewDeleteUserOK() *DeleteUserOK {

	return &DeleteUserOK{}
}

// WithVersion adds the version to the delete user o k response
func (o *DeleteUserOK) WithVersion(version string) *DeleteUserOK {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete user o k response
func (o *DeleteUserOK) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUserNotFoundCode is the HTTP code returned for type DeleteUserNotFound
const DeleteUserNotFoundCode int = 404

/*DeleteUserNotFound User not found

swagger:response deleteUserNotFound
*/
type DeleteUserNotFound struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteUserNotFound creates DeleteUserNotFound with default headers values
func NewDeleteUserNotFound() *DeleteUserNotFound {

	return &DeleteUserNotFound{}
}

// WithVersion adds the version to the delete user not found response
func (o *DeleteUserNotFound) WithVersion(version string) *DeleteUserNotFound {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete user not found response
func (o *DeleteUserNotFound) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteUserInternalServerErrorCode is the HTTP code returned for type DeleteUserInternalServerError
const DeleteUserInternalServerErrorCode int = 500

/*DeleteUserInternalServerError Internal server error

swagger:response deleteUserInternalServerError
*/
type DeleteUserInternalServerError struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteUserInternalServerError creates DeleteUserInternalServerError with default headers values
func NewDeleteUserInternalServerError() *DeleteUserInternalServerError {

	return &DeleteUserInternalServerError{}
}

// WithVersion adds the version to the delete user internal server error response
func (o *DeleteUserInternalServerError) WithVersion(version string) *DeleteUserInternalServerError {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete user internal server error response
func (o *DeleteUserInternalServerError) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
