// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	model "github.com/tetrateio/training/samples/modernbank/microservices/user/pkg/model"
)

// GetUserByUserNameHandlerFunc turns a function with the right signature into a get user by user name handler
type GetUserByUserNameHandlerFunc func(GetUserByUserNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByUserNameHandlerFunc) Handle(params GetUserByUserNameParams) middleware.Responder {
	return fn(params)
}

// GetUserByUserNameHandler interface for that can handle valid get user by user name params
type GetUserByUserNameHandler interface {
	Handle(GetUserByUserNameParams) middleware.Responder
}

// NewGetUserByUserName creates a new http.Handler for the get user by user name operation
func NewGetUserByUserName(ctx *middleware.Context, handler GetUserByUserNameHandler) *GetUserByUserName {
	return &GetUserByUserName{Context: ctx, Handler: handler}
}

/*GetUserByUserName swagger:route GET /users/{username} users getUserByUserName

Get user by user name

*/
type GetUserByUserName struct {
	Context *middleware.Context
	Handler GetUserByUserNameHandler
}

func (o *GetUserByUserName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserByUserNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetUserByUserNameOKBody get user by user name o k body
// swagger:model GetUserByUserNameOKBody
type GetUserByUserNameOKBody struct {
	model.User

	model.Version
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetUserByUserNameOKBody) UnmarshalJSON(raw []byte) error {
	// GetUserByUserNameOKBodyAO0
	var getUserByUserNameOKBodyAO0 model.User
	if err := swag.ReadJSON(raw, &getUserByUserNameOKBodyAO0); err != nil {
		return err
	}
	o.User = getUserByUserNameOKBodyAO0

	// GetUserByUserNameOKBodyAO1
	var getUserByUserNameOKBodyAO1 model.Version
	if err := swag.ReadJSON(raw, &getUserByUserNameOKBodyAO1); err != nil {
		return err
	}
	o.Version = getUserByUserNameOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetUserByUserNameOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getUserByUserNameOKBodyAO0, err := swag.WriteJSON(o.User)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getUserByUserNameOKBodyAO0)

	getUserByUserNameOKBodyAO1, err := swag.WriteJSON(o.Version)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getUserByUserNameOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get user by user name o k body
func (o *GetUserByUserNameOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with model.User
	if err := o.User.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with model.Version
	if err := o.Version.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserByUserNameOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserByUserNameOKBody) UnmarshalBinary(b []byte) error {
	var res GetUserByUserNameOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
