// tslint:disable
/**
 * Modern Bank
 * This is the API exposed to customers of Modern Bank.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    owner: string;
}

export function AccountFromJSON(json: any): Account {
    return {
        'balance': json['balance'],
        'number': json['number'],
        'owner': json['owner'],
    };
}

export function AccountToJSON(value?: Account): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'balance': value.balance,
        'number': value.number,
        'owner': value.owner,
    };
}


