// tslint:disable
/**
 * Modern Bank
 * This is the API exposed to customers of Modern Bank.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface Newtransaction
 */
export interface Newtransaction {
  /**
   *
   * @type {number}
   * @memberof Newtransaction
   */
  amount: number;
  /**
   *
   * @type {number}
   * @memberof Newtransaction
   */
  receiver: number;
  /**
   *
   * @type {number}
   * @memberof Newtransaction
   */
  sender: number;

  /**
   *
   * @type {number}
   * @memberof Newtransaction
   */
  timestamp: number;

  /**
   *
   * @type {number}
   * @memberof Newtransaction
   */
  balance?: number;
}

export function NewtransactionFromJSON(json: any): Newtransaction {
  return {
    amount: json['amount'],
    receiver: json['receiver'],
    sender: json['sender'],
    timestamp: json['timestamp']
  };
}

export function NewtransactionToJSON(value?: Newtransaction): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    amount: value.amount,
    receiver: value.receiver,
    sender: value.sender,
    timestamp: value.timestamp
  };
}
