apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: storefront
spec:
  selector:
    istio: ingressgateway 
    service.istio.io/canonical-name: hipstershop-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "storefront.${INGRESSIP}.sslip.io"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "storefront.${INGRESSIP}.sslip.io"