schemes:
- http
swagger: "2.0"
info:
  description: This is the API exposed to customers of Modern Bank.
  title: Modern Bank
  version: 1.0.0
basePath: /v1
paths:
  /account/{receiver}/received:
    get:
      description: Lists all transactions sent to a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Lists all transactions sent to a given account
      operationId: listTransactionsReceived
      parameters:
      - type: integer
        format: int64
        description: Account number that received the transactions
        name: receiver
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            type: array
            items:
              $ref: '#/definitions/transaction'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "404":
          description: No transactions found
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
  /account/{sender}/sent:
    get:
      description: Lists all transactions sent from a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Lists all transactions sent from a given account
      operationId: listTransactionsSent
      parameters:
      - type: integer
        format: int64
        description: Account number that made the transactions
        name: sender
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            type: array
            items:
              $ref: '#/definitions/transaction'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "404":
          description: No transactions found
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
  /transactions:
    post:
      description: Sends money from one account to another
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - transactions
      summary: Sends money from one account to another
      operationId: CreateTransaction
      parameters:
      - description: Transaction to create
        name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/newtransaction'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transaction'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "400":
          description: Nice try! You can't send negative amounts...
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
  /users:
    post:
      description: Creates a new user
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      summary: Create a new user identity for a customer
      operationId: createUser
      parameters:
      - description: Created user object
        name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/user'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "409":
          description: User alreadys exists
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
  /users/{username}:
    get:
      produces:
      - application/json
      tags:
      - users
      summary: Get user by user name
      operationId: getUserByUserName
      parameters:
      - type: string
        description: The name that needs to be fetched.
        name: username
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            $ref: '#/definitions/user'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "404":
          description: User not found
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
  /users/{username}/accounts:
    get:
      description: Lists all accounts for a given customer
      produces:
      - application/json
      tags:
      - accounts
      summary: Lists all accounts for a given customer
      operationId: listAccounts
      parameters:
      - type: string
        description: Username to fetch the accounts of
        name: username
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            type: array
            items:
              $ref: '#/definitions/account'
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "404":
          description: Owner not found
          headers:
            version:
              type: string
              description: Version of the microservice that responded
        "500":
          description: Internal server error
          headers:
            version:
              type: string
              description: Version of the microservice that responded
definitions:
  account:
    type: object
    required:
    - number
    - balance
    - owner
    - type
    properties:
      balance:
        type: number
        format: currency
      number:
        type: integer
        format: int64
      owner:
        type: string
      type:
        type: string
        enum:
        - cash
        - saving
  newtransaction:
    type: object
    required:
    - sender
    - receiver
    - amount
    properties:
      amount:
        type: number
        format: currency
      receiver:
        type: integer
        format: int64
      sender:
        type: integer
        format: int64
  transaction:
    allOf:
    - type: object
      required:
      - sender
      - receiver
      - amount
      properties:
        amount:
          type: number
          format: currency
        receiver:
          type: integer
          format: int64
        sender:
          type: integer
          format: int64
    - type: object
      required:
      - id
      properties:
        id:
          type: string
  user:
    type: object
    required:
    - username
    - firstName
    - lastName
    - email
    - password
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
tags:
- description: Operations for banking services.
  name: banking
