// Code generated by go-swagger; DO NOT EDIT.

package payment_processing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	model "github.com/tetrateio/training/samples/modernbank/microservices/payment-processing/pkg/model"
)

// NewMakePaymentParams creates a new MakePaymentParams object
// no default values defined in spec.
func NewMakePaymentParams() MakePaymentParams {

	return MakePaymentParams{}
}

// MakePaymentParams contains all the bound params for the make payment operation
// typically these are obtained from a http.Request
//
// swagger:parameters makePayment
type MakePaymentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Payment to make
	  Required: true
	  In: body
	*/
	Body *model.Payment
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMakePaymentParams() beforehand.
func (o *MakePaymentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.Payment
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
