// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/account/pkg/model"
)

// ChangeBalanceReader is a Reader for the ChangeBalance structure.
type ChangeBalanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeBalanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewChangeBalanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewChangeBalanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewChangeBalanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeBalanceOK creates a ChangeBalanceOK with default headers values
func NewChangeBalanceOK() *ChangeBalanceOK {
	return &ChangeBalanceOK{}
}

/*ChangeBalanceOK handles this case with default header values.

OK
*/
type ChangeBalanceOK struct {
	Payload model.Version
}

func (o *ChangeBalanceOK) Error() string {
	return fmt.Sprintf("[PUT /accounts/{number}/balance/{delta}][%d] changeBalanceOK  %+v", 200, o.Payload)
}

func (o *ChangeBalanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeBalanceNotFound creates a ChangeBalanceNotFound with default headers values
func NewChangeBalanceNotFound() *ChangeBalanceNotFound {
	return &ChangeBalanceNotFound{}
}

/*ChangeBalanceNotFound handles this case with default header values.

Account not found
*/
type ChangeBalanceNotFound struct {
}

func (o *ChangeBalanceNotFound) Error() string {
	return fmt.Sprintf("[PUT /accounts/{number}/balance/{delta}][%d] changeBalanceNotFound ", 404)
}

func (o *ChangeBalanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeBalanceInternalServerError creates a ChangeBalanceInternalServerError with default headers values
func NewChangeBalanceInternalServerError() *ChangeBalanceInternalServerError {
	return &ChangeBalanceInternalServerError{}
}

/*ChangeBalanceInternalServerError handles this case with default header values.

Internal server error
*/
type ChangeBalanceInternalServerError struct {
}

func (o *ChangeBalanceInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /accounts/{number}/balance/{delta}][%d] changeBalanceInternalServerError ", 500)
}

func (o *ChangeBalanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
