// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChangeBalanceParams creates a new ChangeBalanceParams object
// with the default values initialized.
func NewChangeBalanceParams() *ChangeBalanceParams {
	var ()
	return &ChangeBalanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeBalanceParamsWithTimeout creates a new ChangeBalanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeBalanceParamsWithTimeout(timeout time.Duration) *ChangeBalanceParams {
	var ()
	return &ChangeBalanceParams{

		timeout: timeout,
	}
}

// NewChangeBalanceParamsWithContext creates a new ChangeBalanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeBalanceParamsWithContext(ctx context.Context) *ChangeBalanceParams {
	var ()
	return &ChangeBalanceParams{

		Context: ctx,
	}
}

// NewChangeBalanceParamsWithHTTPClient creates a new ChangeBalanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeBalanceParamsWithHTTPClient(client *http.Client) *ChangeBalanceParams {
	var ()
	return &ChangeBalanceParams{
		HTTPClient: client,
	}
}

/*ChangeBalanceParams contains all the parameters to send to the API endpoint
for the change balance operation typically these are written to a http.Request
*/
type ChangeBalanceParams struct {

	/*B3*/
	B3 *string
	/*Delta
	  The amount to change the balance by (+/-)

	*/
	Delta float64
	/*Number
	  Account number

	*/
	Number int64
	/*XB3Flags*/
	XB3Flags *string
	/*XB3Parentspanid*/
	XB3Parentspanid *string
	/*XB3Sampled*/
	XB3Sampled *string
	/*XB3SpanID*/
	XB3SpanID *string
	/*XB3Traceid*/
	XB3Traceid *string
	/*XRequestID*/
	XRequestID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change balance params
func (o *ChangeBalanceParams) WithTimeout(timeout time.Duration) *ChangeBalanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change balance params
func (o *ChangeBalanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change balance params
func (o *ChangeBalanceParams) WithContext(ctx context.Context) *ChangeBalanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change balance params
func (o *ChangeBalanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change balance params
func (o *ChangeBalanceParams) WithHTTPClient(client *http.Client) *ChangeBalanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change balance params
func (o *ChangeBalanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithB3 adds the b3 to the change balance params
func (o *ChangeBalanceParams) WithB3(b3 *string) *ChangeBalanceParams {
	o.SetB3(b3)
	return o
}

// SetB3 adds the b3 to the change balance params
func (o *ChangeBalanceParams) SetB3(b3 *string) {
	o.B3 = b3
}

// WithDelta adds the delta to the change balance params
func (o *ChangeBalanceParams) WithDelta(delta float64) *ChangeBalanceParams {
	o.SetDelta(delta)
	return o
}

// SetDelta adds the delta to the change balance params
func (o *ChangeBalanceParams) SetDelta(delta float64) {
	o.Delta = delta
}

// WithNumber adds the number to the change balance params
func (o *ChangeBalanceParams) WithNumber(number int64) *ChangeBalanceParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the change balance params
func (o *ChangeBalanceParams) SetNumber(number int64) {
	o.Number = number
}

// WithXB3Flags adds the xB3Flags to the change balance params
func (o *ChangeBalanceParams) WithXB3Flags(xB3Flags *string) *ChangeBalanceParams {
	o.SetXB3Flags(xB3Flags)
	return o
}

// SetXB3Flags adds the xB3Flags to the change balance params
func (o *ChangeBalanceParams) SetXB3Flags(xB3Flags *string) {
	o.XB3Flags = xB3Flags
}

// WithXB3Parentspanid adds the xB3Parentspanid to the change balance params
func (o *ChangeBalanceParams) WithXB3Parentspanid(xB3Parentspanid *string) *ChangeBalanceParams {
	o.SetXB3Parentspanid(xB3Parentspanid)
	return o
}

// SetXB3Parentspanid adds the xB3Parentspanid to the change balance params
func (o *ChangeBalanceParams) SetXB3Parentspanid(xB3Parentspanid *string) {
	o.XB3Parentspanid = xB3Parentspanid
}

// WithXB3Sampled adds the xB3Sampled to the change balance params
func (o *ChangeBalanceParams) WithXB3Sampled(xB3Sampled *string) *ChangeBalanceParams {
	o.SetXB3Sampled(xB3Sampled)
	return o
}

// SetXB3Sampled adds the xB3Sampled to the change balance params
func (o *ChangeBalanceParams) SetXB3Sampled(xB3Sampled *string) {
	o.XB3Sampled = xB3Sampled
}

// WithXB3SpanID adds the xB3SpanID to the change balance params
func (o *ChangeBalanceParams) WithXB3SpanID(xB3SpanID *string) *ChangeBalanceParams {
	o.SetXB3SpanID(xB3SpanID)
	return o
}

// SetXB3SpanID adds the xB3SpanId to the change balance params
func (o *ChangeBalanceParams) SetXB3SpanID(xB3SpanID *string) {
	o.XB3SpanID = xB3SpanID
}

// WithXB3Traceid adds the xB3Traceid to the change balance params
func (o *ChangeBalanceParams) WithXB3Traceid(xB3Traceid *string) *ChangeBalanceParams {
	o.SetXB3Traceid(xB3Traceid)
	return o
}

// SetXB3Traceid adds the xB3Traceid to the change balance params
func (o *ChangeBalanceParams) SetXB3Traceid(xB3Traceid *string) {
	o.XB3Traceid = xB3Traceid
}

// WithXRequestID adds the xRequestID to the change balance params
func (o *ChangeBalanceParams) WithXRequestID(xRequestID *string) *ChangeBalanceParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the change balance params
func (o *ChangeBalanceParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeBalanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.B3 != nil {

		// header param b3
		if err := r.SetHeaderParam("b3", *o.B3); err != nil {
			return err
		}

	}

	// path param delta
	if err := r.SetPathParam("delta", swag.FormatFloat64(o.Delta)); err != nil {
		return err
	}

	// path param number
	if err := r.SetPathParam("number", swag.FormatInt64(o.Number)); err != nil {
		return err
	}

	if o.XB3Flags != nil {

		// header param x-b3-flags
		if err := r.SetHeaderParam("x-b3-flags", *o.XB3Flags); err != nil {
			return err
		}

	}

	if o.XB3Parentspanid != nil {

		// header param x-b3-parentspanid
		if err := r.SetHeaderParam("x-b3-parentspanid", *o.XB3Parentspanid); err != nil {
			return err
		}

	}

	if o.XB3Sampled != nil {

		// header param x-b3-sampled
		if err := r.SetHeaderParam("x-b3-sampled", *o.XB3Sampled); err != nil {
			return err
		}

	}

	if o.XB3SpanID != nil {

		// header param x-b3-spanId
		if err := r.SetHeaderParam("x-b3-spanId", *o.XB3SpanID); err != nil {
			return err
		}

	}

	if o.XB3Traceid != nil {

		// header param x-b3-traceid
		if err := r.SetHeaderParam("x-b3-traceid", *o.XB3Traceid); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param x-request-id
		if err := r.SetHeaderParam("x-request-id", *o.XRequestID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
