// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/account/pkg/model"
)

// GetAccountByNumberReader is a Reader for the GetAccountByNumber structure.
type GetAccountByNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountByNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccountByNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAccountByNumberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAccountByNumberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountByNumberOK creates a GetAccountByNumberOK with default headers values
func NewGetAccountByNumberOK() *GetAccountByNumberOK {
	return &GetAccountByNumberOK{}
}

/*GetAccountByNumberOK handles this case with default header values.

Success!
*/
type GetAccountByNumberOK struct {
	/*Version of the microservice that responded
	 */
	Version string

	Payload *model.Account
}

func (o *GetAccountByNumberOK) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberOK  %+v", 200, o.Payload)
}

func (o *GetAccountByNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header version
	o.Version = response.GetHeader("version")

	o.Payload = new(model.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountByNumberNotFound creates a GetAccountByNumberNotFound with default headers values
func NewGetAccountByNumberNotFound() *GetAccountByNumberNotFound {
	return &GetAccountByNumberNotFound{}
}

/*GetAccountByNumberNotFound handles this case with default header values.

Account not found
*/
type GetAccountByNumberNotFound struct {
	/*Version of the microservice that responded
	 */
	Version string
}

func (o *GetAccountByNumberNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberNotFound ", 404)
}

func (o *GetAccountByNumberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header version
	o.Version = response.GetHeader("version")

	return nil
}

// NewGetAccountByNumberInternalServerError creates a GetAccountByNumberInternalServerError with default headers values
func NewGetAccountByNumberInternalServerError() *GetAccountByNumberInternalServerError {
	return &GetAccountByNumberInternalServerError{}
}

/*GetAccountByNumberInternalServerError handles this case with default header values.

Internal server error
*/
type GetAccountByNumberInternalServerError struct {
	/*Version of the microservice that responded
	 */
	Version string
}

func (o *GetAccountByNumberInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberInternalServerError ", 500)
}

func (o *GetAccountByNumberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header version
	o.Version = response.GetHeader("version")

	return nil
}
