// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/account/pkg/model"
)

// GetAccountByNumberReader is a Reader for the GetAccountByNumber structure.
type GetAccountByNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountByNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccountByNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAccountByNumberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAccountByNumberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountByNumberOK creates a GetAccountByNumberOK with default headers values
func NewGetAccountByNumberOK() *GetAccountByNumberOK {
	return &GetAccountByNumberOK{}
}

/*GetAccountByNumberOK handles this case with default header values.

Success!
*/
type GetAccountByNumberOK struct {
	Payload *GetAccountByNumberOKBody
}

func (o *GetAccountByNumberOK) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberOK  %+v", 200, o.Payload)
}

func (o *GetAccountByNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAccountByNumberOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountByNumberNotFound creates a GetAccountByNumberNotFound with default headers values
func NewGetAccountByNumberNotFound() *GetAccountByNumberNotFound {
	return &GetAccountByNumberNotFound{}
}

/*GetAccountByNumberNotFound handles this case with default header values.

Account not found
*/
type GetAccountByNumberNotFound struct {
}

func (o *GetAccountByNumberNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberNotFound ", 404)
}

func (o *GetAccountByNumberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAccountByNumberInternalServerError creates a GetAccountByNumberInternalServerError with default headers values
func NewGetAccountByNumberInternalServerError() *GetAccountByNumberInternalServerError {
	return &GetAccountByNumberInternalServerError{}
}

/*GetAccountByNumberInternalServerError handles this case with default header values.

Internal server error
*/
type GetAccountByNumberInternalServerError struct {
}

func (o *GetAccountByNumberInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{owner}/accounts/{number}][%d] getAccountByNumberInternalServerError ", 500)
}

func (o *GetAccountByNumberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetAccountByNumberOKBody get account by number o k body
swagger:model GetAccountByNumberOKBody
*/
type GetAccountByNumberOKBody struct {
	model.Account

	model.Version
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAccountByNumberOKBody) UnmarshalJSON(raw []byte) error {
	// GetAccountByNumberOKBodyAO0
	var getAccountByNumberOKBodyAO0 model.Account
	if err := swag.ReadJSON(raw, &getAccountByNumberOKBodyAO0); err != nil {
		return err
	}
	o.Account = getAccountByNumberOKBodyAO0

	// GetAccountByNumberOKBodyAO1
	var getAccountByNumberOKBodyAO1 model.Version
	if err := swag.ReadJSON(raw, &getAccountByNumberOKBodyAO1); err != nil {
		return err
	}
	o.Version = getAccountByNumberOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAccountByNumberOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getAccountByNumberOKBodyAO0, err := swag.WriteJSON(o.Account)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getAccountByNumberOKBodyAO0)

	getAccountByNumberOKBodyAO1, err := swag.WriteJSON(o.Version)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getAccountByNumberOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get account by number o k body
func (o *GetAccountByNumberOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with model.Account
	if err := o.Account.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with model.Version
	if err := o.Version.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetAccountByNumberOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAccountByNumberOKBody) UnmarshalBinary(b []byte) error {
	var res GetAccountByNumberOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
