// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChangeBalanceParams creates a new ChangeBalanceParams object
// no default values defined in spec.
func NewChangeBalanceParams() ChangeBalanceParams {

	return ChangeBalanceParams{}
}

// ChangeBalanceParams contains all the bound params for the change balance operation
// typically these are obtained from a http.Request
//
// swagger:parameters changeBalance
type ChangeBalanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: header
	*/
	B3 *string
	/*The amount to change the balance by (+/-)
	  Required: true
	  In: path
	*/
	Delta float64
	/*Account number
	  Required: true
	  In: path
	*/
	Number int64
	/*
	  In: header
	*/
	XB3Flags *string
	/*
	  In: header
	*/
	XB3Parentspanid *string
	/*
	  In: header
	*/
	XB3Sampled *string
	/*
	  In: header
	*/
	XB3SpanID *string
	/*
	  In: header
	*/
	XB3Traceid *string
	/*
	  In: header
	*/
	XRequestID *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewChangeBalanceParams() beforehand.
func (o *ChangeBalanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindB3(r.Header[http.CanonicalHeaderKey("b3")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rDelta, rhkDelta, _ := route.Params.GetOK("delta")
	if err := o.bindDelta(rDelta, rhkDelta, route.Formats); err != nil {
		res = append(res, err)
	}

	rNumber, rhkNumber, _ := route.Params.GetOK("number")
	if err := o.bindNumber(rNumber, rhkNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Flags(r.Header[http.CanonicalHeaderKey("x-b3-flags")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Parentspanid(r.Header[http.CanonicalHeaderKey("x-b3-parentspanid")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Sampled(r.Header[http.CanonicalHeaderKey("x-b3-sampled")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3SpanID(r.Header[http.CanonicalHeaderKey("x-b3-spanId")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Traceid(r.Header[http.CanonicalHeaderKey("x-b3-traceid")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXRequestID(r.Header[http.CanonicalHeaderKey("x-request-id")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindB3 binds and validates parameter B3 from header.
func (o *ChangeBalanceParams) bindB3(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.B3 = &raw

	return nil
}

// bindDelta binds and validates parameter Delta from path.
func (o *ChangeBalanceParams) bindDelta(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("delta", "path", "float64", raw)
	}
	o.Delta = value

	return nil
}

// bindNumber binds and validates parameter Number from path.
func (o *ChangeBalanceParams) bindNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("number", "path", "int64", raw)
	}
	o.Number = value

	return nil
}

// bindXB3Flags binds and validates parameter XB3Flags from header.
func (o *ChangeBalanceParams) bindXB3Flags(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Flags = &raw

	return nil
}

// bindXB3Parentspanid binds and validates parameter XB3Parentspanid from header.
func (o *ChangeBalanceParams) bindXB3Parentspanid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Parentspanid = &raw

	return nil
}

// bindXB3Sampled binds and validates parameter XB3Sampled from header.
func (o *ChangeBalanceParams) bindXB3Sampled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Sampled = &raw

	return nil
}

// bindXB3SpanID binds and validates parameter XB3SpanID from header.
func (o *ChangeBalanceParams) bindXB3SpanID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3SpanID = &raw

	return nil
}

// bindXB3Traceid binds and validates parameter XB3Traceid from header.
func (o *ChangeBalanceParams) bindXB3Traceid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Traceid = &raw

	return nil
}

// bindXRequestID binds and validates parameter XRequestID from header.
func (o *ChangeBalanceParams) bindXRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XRequestID = &raw

	return nil
}
