// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChangeBalanceParams creates a new ChangeBalanceParams object
// no default values defined in spec.
func NewChangeBalanceParams() ChangeBalanceParams {

	return ChangeBalanceParams{}
}

// ChangeBalanceParams contains all the bound params for the change balance operation
// typically these are obtained from a http.Request
//
// swagger:parameters changeBalance
type ChangeBalanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The amount to change the balance by (+/-)
	  Required: true
	  In: path
	*/
	Delta float64
	/*Account number
	  Required: true
	  In: path
	*/
	Number int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewChangeBalanceParams() beforehand.
func (o *ChangeBalanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDelta, rhkDelta, _ := route.Params.GetOK("delta")
	if err := o.bindDelta(rDelta, rhkDelta, route.Formats); err != nil {
		res = append(res, err)
	}

	rNumber, rhkNumber, _ := route.Params.GetOK("number")
	if err := o.bindNumber(rNumber, rhkNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDelta binds and validates parameter Delta from path.
func (o *ChangeBalanceParams) bindDelta(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("delta", "path", "float64", raw)
	}
	o.Delta = value

	return nil
}

// bindNumber binds and validates parameter Number from path.
func (o *ChangeBalanceParams) bindNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("number", "path", "int64", raw)
	}
	o.Number = value

	return nil
}
