// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	model "github.com/tetrateio/training/samples/modernbank/microservices/account/pkg/model"
)

// CreateAccountHandlerFunc turns a function with the right signature into a create account handler
type CreateAccountHandlerFunc func(CreateAccountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAccountHandlerFunc) Handle(params CreateAccountParams) middleware.Responder {
	return fn(params)
}

// CreateAccountHandler interface for that can handle valid create account params
type CreateAccountHandler interface {
	Handle(CreateAccountParams) middleware.Responder
}

// NewCreateAccount creates a new http.Handler for the create account operation
func NewCreateAccount(ctx *middleware.Context, handler CreateAccountHandler) *CreateAccount {
	return &CreateAccount{Context: ctx, Handler: handler}
}

/*CreateAccount swagger:route POST /users/{owner}/accounts accounts createAccount

Create a new account for a customer

Creates a new account for a given customer

*/
type CreateAccount struct {
	Context *middleware.Context
	Handler CreateAccountHandler
}

func (o *CreateAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateAccountParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateAccountCreatedBody create account created body
// swagger:model CreateAccountCreatedBody
type CreateAccountCreatedBody struct {
	model.Account

	model.Version
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *CreateAccountCreatedBody) UnmarshalJSON(raw []byte) error {
	// CreateAccountCreatedBodyAO0
	var createAccountCreatedBodyAO0 model.Account
	if err := swag.ReadJSON(raw, &createAccountCreatedBodyAO0); err != nil {
		return err
	}
	o.Account = createAccountCreatedBodyAO0

	// CreateAccountCreatedBodyAO1
	var createAccountCreatedBodyAO1 model.Version
	if err := swag.ReadJSON(raw, &createAccountCreatedBodyAO1); err != nil {
		return err
	}
	o.Version = createAccountCreatedBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o CreateAccountCreatedBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	createAccountCreatedBodyAO0, err := swag.WriteJSON(o.Account)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, createAccountCreatedBodyAO0)

	createAccountCreatedBodyAO1, err := swag.WriteJSON(o.Version)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, createAccountCreatedBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this create account created body
func (o *CreateAccountCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with model.Account
	if err := o.Account.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with model.Version
	if err := o.Version.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *CreateAccountCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateAccountCreatedBody) UnmarshalBinary(b []byte) error {
	var res CreateAccountCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
