// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateAccountParams creates a new CreateAccountParams object
// no default values defined in spec.
func NewCreateAccountParams() CreateAccountParams {

	return CreateAccountParams{}
}

// CreateAccountParams contains all the bound params for the create account operation
// typically these are obtained from a http.Request
//
// swagger:parameters createAccount
type CreateAccountParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: header
	*/
	B3 *string
	/*Owner of the account
	  Required: true
	  In: query
	*/
	Owner string
	/*
	  Required: true
	  In: query
	*/
	Type string
	/*
	  In: header
	*/
	XB3Flags *string
	/*
	  In: header
	*/
	XB3Parentspanid *string
	/*
	  In: header
	*/
	XB3Sampled *string
	/*
	  In: header
	*/
	XB3SpanID *string
	/*
	  In: header
	*/
	XB3Traceid *string
	/*
	  In: header
	*/
	XRequestID *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateAccountParams() beforehand.
func (o *CreateAccountParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindB3(r.Header[http.CanonicalHeaderKey("b3")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	qOwner, qhkOwner, _ := qs.GetOK("owner")
	if err := o.bindOwner(qOwner, qhkOwner, route.Formats); err != nil {
		res = append(res, err)
	}

	qType, qhkType, _ := qs.GetOK("type")
	if err := o.bindType(qType, qhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Flags(r.Header[http.CanonicalHeaderKey("x-b3-flags")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Parentspanid(r.Header[http.CanonicalHeaderKey("x-b3-parentspanid")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Sampled(r.Header[http.CanonicalHeaderKey("x-b3-sampled")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3SpanID(r.Header[http.CanonicalHeaderKey("x-b3-spanId")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXB3Traceid(r.Header[http.CanonicalHeaderKey("x-b3-traceid")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXRequestID(r.Header[http.CanonicalHeaderKey("x-request-id")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindB3 binds and validates parameter B3 from header.
func (o *CreateAccountParams) bindB3(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.B3 = &raw

	return nil
}

// bindOwner binds and validates parameter Owner from query.
func (o *CreateAccountParams) bindOwner(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("owner", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("owner", "query", raw); err != nil {
		return err
	}

	o.Owner = raw

	return nil
}

// bindType binds and validates parameter Type from query.
func (o *CreateAccountParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("type", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("type", "query", raw); err != nil {
		return err
	}

	o.Type = raw

	if err := o.validateType(formats); err != nil {
		return err
	}

	return nil
}

// validateType carries on validations for parameter Type
func (o *CreateAccountParams) validateType(formats strfmt.Registry) error {

	if err := validate.Enum("type", "query", o.Type, []interface{}{"cash", "saving"}); err != nil {
		return err
	}

	return nil
}

// bindXB3Flags binds and validates parameter XB3Flags from header.
func (o *CreateAccountParams) bindXB3Flags(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Flags = &raw

	return nil
}

// bindXB3Parentspanid binds and validates parameter XB3Parentspanid from header.
func (o *CreateAccountParams) bindXB3Parentspanid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Parentspanid = &raw

	return nil
}

// bindXB3Sampled binds and validates parameter XB3Sampled from header.
func (o *CreateAccountParams) bindXB3Sampled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Sampled = &raw

	return nil
}

// bindXB3SpanID binds and validates parameter XB3SpanID from header.
func (o *CreateAccountParams) bindXB3SpanID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3SpanID = &raw

	return nil
}

// bindXB3Traceid binds and validates parameter XB3Traceid from header.
func (o *CreateAccountParams) bindXB3Traceid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XB3Traceid = &raw

	return nil
}

// bindXRequestID binds and validates parameter XRequestID from header.
func (o *CreateAccountParams) bindXRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XRequestID = &raw

	return nil
}
