// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAccountOKCode is the HTTP code returned for type DeleteAccountOK
const DeleteAccountOKCode int = 200

/*DeleteAccountOK Aaaaand it's gone!

swagger:response deleteAccountOK
*/
type DeleteAccountOK struct {
}

// NewDeleteAccountOK creates DeleteAccountOK with default headers values
func NewDeleteAccountOK() *DeleteAccountOK {

	return &DeleteAccountOK{}
}

// WriteResponse to the client
func (o *DeleteAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAccountNotFoundCode is the HTTP code returned for type DeleteAccountNotFound
const DeleteAccountNotFoundCode int = 404

/*DeleteAccountNotFound Account not found

swagger:response deleteAccountNotFound
*/
type DeleteAccountNotFound struct {
}

// NewDeleteAccountNotFound creates DeleteAccountNotFound with default headers values
func NewDeleteAccountNotFound() *DeleteAccountNotFound {

	return &DeleteAccountNotFound{}
}

// WriteResponse to the client
func (o *DeleteAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteAccountInternalServerErrorCode is the HTTP code returned for type DeleteAccountInternalServerError
const DeleteAccountInternalServerErrorCode int = 500

/*DeleteAccountInternalServerError Internal server error

swagger:response deleteAccountInternalServerError
*/
type DeleteAccountInternalServerError struct {
}

// NewDeleteAccountInternalServerError creates DeleteAccountInternalServerError with default headers values
func NewDeleteAccountInternalServerError() *DeleteAccountInternalServerError {

	return &DeleteAccountInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
