// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAccountOKCode is the HTTP code returned for type DeleteAccountOK
const DeleteAccountOKCode int = 200

/*DeleteAccountOK Aaaaand it's gone!

swagger:response deleteAccountOK
*/
type DeleteAccountOK struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteAccountOK creates DeleteAccountOK with default headers values
func NewDeleteAccountOK() *DeleteAccountOK {

	return &DeleteAccountOK{}
}

// WithVersion adds the version to the delete account o k response
func (o *DeleteAccountOK) WithVersion(version string) *DeleteAccountOK {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete account o k response
func (o *DeleteAccountOK) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAccountNotFoundCode is the HTTP code returned for type DeleteAccountNotFound
const DeleteAccountNotFoundCode int = 404

/*DeleteAccountNotFound Account not found

swagger:response deleteAccountNotFound
*/
type DeleteAccountNotFound struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteAccountNotFound creates DeleteAccountNotFound with default headers values
func NewDeleteAccountNotFound() *DeleteAccountNotFound {

	return &DeleteAccountNotFound{}
}

// WithVersion adds the version to the delete account not found response
func (o *DeleteAccountNotFound) WithVersion(version string) *DeleteAccountNotFound {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete account not found response
func (o *DeleteAccountNotFound) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteAccountInternalServerErrorCode is the HTTP code returned for type DeleteAccountInternalServerError
const DeleteAccountInternalServerErrorCode int = 500

/*DeleteAccountInternalServerError Internal server error

swagger:response deleteAccountInternalServerError
*/
type DeleteAccountInternalServerError struct {
	/*Version of the microservice that responded

	 */
	Version string `json:"version"`
}

// NewDeleteAccountInternalServerError creates DeleteAccountInternalServerError with default headers values
func NewDeleteAccountInternalServerError() *DeleteAccountInternalServerError {

	return &DeleteAccountInternalServerError{}
}

// WithVersion adds the version to the delete account internal server error response
func (o *DeleteAccountInternalServerError) WithVersion(version string) *DeleteAccountInternalServerError {
	o.Version = version
	return o
}

// SetVersion sets the version to the delete account internal server error response
func (o *DeleteAccountInternalServerError) SetVersion(version string) {
	o.Version = version
}

// WriteResponse to the client
func (o *DeleteAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header version

	version := o.Version
	if version != "" {
		rw.Header().Set("version", version)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
