// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	model "github.com/tetrateio/training/samples/modernbank/microservices/account/pkg/model"
)

// ListAccountsHandlerFunc turns a function with the right signature into a list accounts handler
type ListAccountsHandlerFunc func(ListAccountsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAccountsHandlerFunc) Handle(params ListAccountsParams) middleware.Responder {
	return fn(params)
}

// ListAccountsHandler interface for that can handle valid list accounts params
type ListAccountsHandler interface {
	Handle(ListAccountsParams) middleware.Responder
}

// NewListAccounts creates a new http.Handler for the list accounts operation
func NewListAccounts(ctx *middleware.Context, handler ListAccountsHandler) *ListAccounts {
	return &ListAccounts{Context: ctx, Handler: handler}
}

/*ListAccounts swagger:route GET /users/{owner}/accounts accounts listAccounts

Lists all accounts for a given customer

Lists all accounts for a given customer

*/
type ListAccounts struct {
	Context *middleware.Context
	Handler ListAccountsHandler
}

func (o *ListAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAccountsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ListAccountsOKBody list accounts o k body
// swagger:model ListAccountsOKBody
type ListAccountsOKBody struct {
	ListAccountsOKBodyAllOf0

	model.Version
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListAccountsOKBody) UnmarshalJSON(raw []byte) error {
	// ListAccountsOKBodyAO0
	var listAccountsOKBodyAO0 ListAccountsOKBodyAllOf0
	if err := swag.ReadJSON(raw, &listAccountsOKBodyAO0); err != nil {
		return err
	}
	o.ListAccountsOKBodyAllOf0 = listAccountsOKBodyAO0

	// ListAccountsOKBodyAO1
	var listAccountsOKBodyAO1 model.Version
	if err := swag.ReadJSON(raw, &listAccountsOKBodyAO1); err != nil {
		return err
	}
	o.Version = listAccountsOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListAccountsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	listAccountsOKBodyAO0, err := swag.WriteJSON(o.ListAccountsOKBodyAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, listAccountsOKBodyAO0)

	listAccountsOKBodyAO1, err := swag.WriteJSON(o.Version)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, listAccountsOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list accounts o k body
func (o *ListAccountsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ListAccountsOKBodyAllOf0
	if err := o.ListAccountsOKBodyAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with model.Version
	if err := o.Version.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *ListAccountsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListAccountsOKBody) UnmarshalBinary(b []byte) error {
	var res ListAccountsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ListAccountsOKBodyAllOf0 list accounts o k body all of0
// swagger:model ListAccountsOKBodyAllOf0
type ListAccountsOKBodyAllOf0 []*model.Account

// Validate validates this list accounts o k body all of0
func (o ListAccountsOKBodyAllOf0) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(o); i++ {
		if swag.IsZero(o[i]) { // not required
			continue
		}

		if o[i] != nil {
			if err := o[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
