// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAccountsParams creates a new ListAccountsParams object
// no default values defined in spec.
func NewListAccountsParams() ListAccountsParams {

	return ListAccountsParams{}
}

// ListAccountsParams contains all the bound params for the list accounts operation
// typically these are obtained from a http.Request
//
// swagger:parameters listAccounts
type ListAccountsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Owner of the accounts
	  Required: true
	  In: query
	*/
	Owner string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListAccountsParams() beforehand.
func (o *ListAccountsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qOwner, qhkOwner, _ := qs.GetOK("owner")
	if err := o.bindOwner(qOwner, qhkOwner, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOwner binds and validates parameter Owner from query.
func (o *ListAccountsParams) bindOwner(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("owner", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("owner", "query", raw); err != nil {
		return err
	}

	o.Owner = raw

	return nil
}
