swagger: "2.0"
info:
  description: "This is the Account Microservice, responsible for managing accounts and their balances in Modern Bank."
  version: "1.0.0"
  title: "Account"
host: "account"
basePath: "/v1"
tags:
- name: "account"
  description: "Operations about Accounts"
schemes:
- "http"
paths:
  /accounts/{number}/balance/{delta}:
    $ref: "./paths/account/accountsByNumberBalanceDelta.yaml"
  /accounts:
    $ref: "./paths/account/accounts.yaml"
  /health:
    $ref: "./paths/shared/health.yaml"
