swagger: "2.0"
info:
  description: "This is the API exposed to customers of Modern Bank."
  version: "1.0.0"
  title: "Modern Bank"
basePath: "/v1"
tags:
- name: "banking"
  description: "Operations for banking services."
schemes:
- "http"
paths:
  /users:
    $ref: "./paths/user/users.yaml"
  /users/{username}:
    $ref: "./paths/user/usersByUsername.yaml"
  /users/{username}/accounts:
    $ref: "./paths/user/accountsByUsername.yaml"
  /transactions:
    $ref: "./paths/transaction/transactions.yaml"
  /account/{sender}/sent:
    $ref: "./paths/transaction/transactionsSentFromAccount.yaml"
  /account/{receiver}/received:
    $ref: "./paths/transaction/transactionsReceivedToAccount.yaml"
