swagger: "2.0"
info:
  description: "This is the Transaction Log Microservice, an immutable append-only Transaction Log in Modern Bank."
  version: "1.0.0"
  title: "Transaction Log"
host: "transaction-log"
basePath: "/v1"
tags:
- name: "transaction-log"
  description: "Operations about transactions"
schemes:
- "http"
paths:
  /transactions:
    $ref: "./paths/transaction/transactions.yaml"
  /transactions/account/{sender}/sent:
    $ref: "./paths/transaction/transactionsSentFromAccount.yaml"
  /transactions/account/{receiver}/received:
    $ref: "./paths/transaction/transactionsReceivedToAccount.yaml"
  /health:
    $ref: "./paths/shared/health.yaml"
