swagger: "2.0"
info:
  description: "This is the User Microservice, responsible for managing Users in Modern Bank."
  version: "1.0.0"
  title: "User"
host: "users"
basePath: "/v1"
tags:
- name: "user"
  description: "Operations about users"
schemes:
- "http"
paths:
  /users:
    $ref: "./paths/user/users.yaml"
  /users/{username}:
    $ref: "./paths/user/usersByUsername.yaml"
  /users/{username}/accounts:
    $ref: "./paths/user/accountsByUsername.yaml"
  /health:
    $ref: "./paths/shared/health.yaml"
