apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
spec:
  hosts:
  - "*"
  gateways:
  - ingress
  http:
  - match:
    - uri:
        prefix: /v1/users
    route:
    - destination:
        host: user
        port: 
          number: 80
        subset: v1
      weight: 100
    - destination:
        host: user
        port: 
          number: 80
        subset: v2
      weight: 0
