// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/transaction/pkg/model"
)

// NewCreateTransactionParams creates a new CreateTransactionParams object
// with the default values initialized.
func NewCreateTransactionParams() *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTransactionParamsWithTimeout creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTransactionParamsWithTimeout(timeout time.Duration) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		timeout: timeout,
	}
}

// NewCreateTransactionParamsWithContext creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTransactionParamsWithContext(ctx context.Context) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		Context: ctx,
	}
}

// NewCreateTransactionParamsWithHTTPClient creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTransactionParamsWithHTTPClient(client *http.Client) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{
		HTTPClient: client,
	}
}

/*CreateTransactionParams contains all the parameters to send to the API endpoint
for the create transaction operation typically these are written to a http.Request
*/
type CreateTransactionParams struct {

	/*B3*/
	B3 *string
	/*Body
	  Transaction to create

	*/
	Body *model.Newtransaction
	/*XB3Flags*/
	XB3Flags *string
	/*XB3Parentspanid*/
	XB3Parentspanid *string
	/*XB3Sampled*/
	XB3Sampled *string
	/*XB3SpanID*/
	XB3SpanID *string
	/*XB3Traceid*/
	XB3Traceid *string
	/*XRequestID*/
	XRequestID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create transaction params
func (o *CreateTransactionParams) WithTimeout(timeout time.Duration) *CreateTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create transaction params
func (o *CreateTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create transaction params
func (o *CreateTransactionParams) WithContext(ctx context.Context) *CreateTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create transaction params
func (o *CreateTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create transaction params
func (o *CreateTransactionParams) WithHTTPClient(client *http.Client) *CreateTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create transaction params
func (o *CreateTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithB3 adds the b3 to the create transaction params
func (o *CreateTransactionParams) WithB3(b3 *string) *CreateTransactionParams {
	o.SetB3(b3)
	return o
}

// SetB3 adds the b3 to the create transaction params
func (o *CreateTransactionParams) SetB3(b3 *string) {
	o.B3 = b3
}

// WithBody adds the body to the create transaction params
func (o *CreateTransactionParams) WithBody(body *model.Newtransaction) *CreateTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create transaction params
func (o *CreateTransactionParams) SetBody(body *model.Newtransaction) {
	o.Body = body
}

// WithXB3Flags adds the xB3Flags to the create transaction params
func (o *CreateTransactionParams) WithXB3Flags(xB3Flags *string) *CreateTransactionParams {
	o.SetXB3Flags(xB3Flags)
	return o
}

// SetXB3Flags adds the xB3Flags to the create transaction params
func (o *CreateTransactionParams) SetXB3Flags(xB3Flags *string) {
	o.XB3Flags = xB3Flags
}

// WithXB3Parentspanid adds the xB3Parentspanid to the create transaction params
func (o *CreateTransactionParams) WithXB3Parentspanid(xB3Parentspanid *string) *CreateTransactionParams {
	o.SetXB3Parentspanid(xB3Parentspanid)
	return o
}

// SetXB3Parentspanid adds the xB3Parentspanid to the create transaction params
func (o *CreateTransactionParams) SetXB3Parentspanid(xB3Parentspanid *string) {
	o.XB3Parentspanid = xB3Parentspanid
}

// WithXB3Sampled adds the xB3Sampled to the create transaction params
func (o *CreateTransactionParams) WithXB3Sampled(xB3Sampled *string) *CreateTransactionParams {
	o.SetXB3Sampled(xB3Sampled)
	return o
}

// SetXB3Sampled adds the xB3Sampled to the create transaction params
func (o *CreateTransactionParams) SetXB3Sampled(xB3Sampled *string) {
	o.XB3Sampled = xB3Sampled
}

// WithXB3SpanID adds the xB3SpanID to the create transaction params
func (o *CreateTransactionParams) WithXB3SpanID(xB3SpanID *string) *CreateTransactionParams {
	o.SetXB3SpanID(xB3SpanID)
	return o
}

// SetXB3SpanID adds the xB3SpanId to the create transaction params
func (o *CreateTransactionParams) SetXB3SpanID(xB3SpanID *string) {
	o.XB3SpanID = xB3SpanID
}

// WithXB3Traceid adds the xB3Traceid to the create transaction params
func (o *CreateTransactionParams) WithXB3Traceid(xB3Traceid *string) *CreateTransactionParams {
	o.SetXB3Traceid(xB3Traceid)
	return o
}

// SetXB3Traceid adds the xB3Traceid to the create transaction params
func (o *CreateTransactionParams) SetXB3Traceid(xB3Traceid *string) {
	o.XB3Traceid = xB3Traceid
}

// WithXRequestID adds the xRequestID to the create transaction params
func (o *CreateTransactionParams) WithXRequestID(xRequestID *string) *CreateTransactionParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create transaction params
func (o *CreateTransactionParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.B3 != nil {

		// header param b3
		if err := r.SetHeaderParam("b3", *o.B3); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.XB3Flags != nil {

		// header param x-b3-flags
		if err := r.SetHeaderParam("x-b3-flags", *o.XB3Flags); err != nil {
			return err
		}

	}

	if o.XB3Parentspanid != nil {

		// header param x-b3-parentspanid
		if err := r.SetHeaderParam("x-b3-parentspanid", *o.XB3Parentspanid); err != nil {
			return err
		}

	}

	if o.XB3Sampled != nil {

		// header param x-b3-sampled
		if err := r.SetHeaderParam("x-b3-sampled", *o.XB3Sampled); err != nil {
			return err
		}

	}

	if o.XB3SpanID != nil {

		// header param x-b3-spanId
		if err := r.SetHeaderParam("x-b3-spanId", *o.XB3SpanID); err != nil {
			return err
		}

	}

	if o.XB3Traceid != nil {

		// header param x-b3-traceid
		if err := r.SetHeaderParam("x-b3-traceid", *o.XB3Traceid); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param x-request-id
		if err := r.SetHeaderParam("x-request-id", *o.XRequestID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
