// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/transaction/pkg/model"
)

// NewCreateTransactionParams creates a new CreateTransactionParams object
// with the default values initialized.
func NewCreateTransactionParams() *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTransactionParamsWithTimeout creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTransactionParamsWithTimeout(timeout time.Duration) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		timeout: timeout,
	}
}

// NewCreateTransactionParamsWithContext creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTransactionParamsWithContext(ctx context.Context) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{

		Context: ctx,
	}
}

// NewCreateTransactionParamsWithHTTPClient creates a new CreateTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTransactionParamsWithHTTPClient(client *http.Client) *CreateTransactionParams {
	var ()
	return &CreateTransactionParams{
		HTTPClient: client,
	}
}

/*CreateTransactionParams contains all the parameters to send to the API endpoint
for the create transaction operation typically these are written to a http.Request
*/
type CreateTransactionParams struct {

	/*Body
	  Created transaction

	*/
	Body *model.NewTransaction

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create transaction params
func (o *CreateTransactionParams) WithTimeout(timeout time.Duration) *CreateTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create transaction params
func (o *CreateTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create transaction params
func (o *CreateTransactionParams) WithContext(ctx context.Context) *CreateTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create transaction params
func (o *CreateTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create transaction params
func (o *CreateTransactionParams) WithHTTPClient(client *http.Client) *CreateTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create transaction params
func (o *CreateTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create transaction params
func (o *CreateTransactionParams) WithBody(body *model.NewTransaction) *CreateTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create transaction params
func (o *CreateTransactionParams) SetBody(body *model.NewTransaction) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
