// Code generated by go-swagger; DO NOT EDIT.

/*
Package server Transaction Log
This is the Transaction Log Microservice, an immutable append-only Transaction Log in Modern Bank.


    Schemes:
      http
    Host: transaction-log
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package server
