// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListTransactionsSentOKCode is the HTTP code returned for type ListTransactionsSentOK
const ListTransactionsSentOKCode int = 200

/*ListTransactionsSentOK Success!

swagger:response listTransactionsSentOK
*/
type ListTransactionsSentOK struct {

	/*
	  In: Body
	*/
	Payload *ListTransactionsSentOKBody `json:"body,omitempty"`
}

// NewListTransactionsSentOK creates ListTransactionsSentOK with default headers values
func NewListTransactionsSentOK() *ListTransactionsSentOK {

	return &ListTransactionsSentOK{}
}

// WithPayload adds the payload to the list transactions sent o k response
func (o *ListTransactionsSentOK) WithPayload(payload *ListTransactionsSentOKBody) *ListTransactionsSentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list transactions sent o k response
func (o *ListTransactionsSentOK) SetPayload(payload *ListTransactionsSentOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTransactionsSentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListTransactionsSentNotFoundCode is the HTTP code returned for type ListTransactionsSentNotFound
const ListTransactionsSentNotFoundCode int = 404

/*ListTransactionsSentNotFound No transactions found

swagger:response listTransactionsSentNotFound
*/
type ListTransactionsSentNotFound struct {
}

// NewListTransactionsSentNotFound creates ListTransactionsSentNotFound with default headers values
func NewListTransactionsSentNotFound() *ListTransactionsSentNotFound {

	return &ListTransactionsSentNotFound{}
}

// WriteResponse to the client
func (o *ListTransactionsSentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ListTransactionsSentInternalServerErrorCode is the HTTP code returned for type ListTransactionsSentInternalServerError
const ListTransactionsSentInternalServerErrorCode int = 500

/*ListTransactionsSentInternalServerError Internal server error

swagger:response listTransactionsSentInternalServerError
*/
type ListTransactionsSentInternalServerError struct {
}

// NewListTransactionsSentInternalServerError creates ListTransactionsSentInternalServerError with default headers values
func NewListTransactionsSentInternalServerError() *ListTransactionsSentInternalServerError {

	return &ListTransactionsSentInternalServerError{}
}

// WriteResponse to the client
func (o *ListTransactionsSentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
