// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	model "github.com/tetrateio/training/samples/modernbank/microservices/transaction-log/pkg/model"
)

// ListTransactionsReceivedHandlerFunc turns a function with the right signature into a list transactions received handler
type ListTransactionsReceivedHandlerFunc func(ListTransactionsReceivedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListTransactionsReceivedHandlerFunc) Handle(params ListTransactionsReceivedParams) middleware.Responder {
	return fn(params)
}

// ListTransactionsReceivedHandler interface for that can handle valid list transactions received params
type ListTransactionsReceivedHandler interface {
	Handle(ListTransactionsReceivedParams) middleware.Responder
}

// NewListTransactionsReceived creates a new http.Handler for the list transactions received operation
func NewListTransactionsReceived(ctx *middleware.Context, handler ListTransactionsReceivedHandler) *ListTransactionsReceived {
	return &ListTransactionsReceived{Context: ctx, Handler: handler}
}

/*ListTransactionsReceived swagger:route GET /account/{receiver}/received transactions listTransactionsReceived

Lists all transactions sent to a given account

Lists all transactions sent to a given account

*/
type ListTransactionsReceived struct {
	Context *middleware.Context
	Handler ListTransactionsReceivedHandler
}

func (o *ListTransactionsReceived) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListTransactionsReceivedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ListTransactionsReceivedOKBody list transactions received o k body
// swagger:model ListTransactionsReceivedOKBody
type ListTransactionsReceivedOKBody struct {
	ListTransactionsReceivedOKBodyAllOf0

	model.Version
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListTransactionsReceivedOKBody) UnmarshalJSON(raw []byte) error {
	// ListTransactionsReceivedOKBodyAO0
	var listTransactionsReceivedOKBodyAO0 ListTransactionsReceivedOKBodyAllOf0
	if err := swag.ReadJSON(raw, &listTransactionsReceivedOKBodyAO0); err != nil {
		return err
	}
	o.ListTransactionsReceivedOKBodyAllOf0 = listTransactionsReceivedOKBodyAO0

	// ListTransactionsReceivedOKBodyAO1
	var listTransactionsReceivedOKBodyAO1 model.Version
	if err := swag.ReadJSON(raw, &listTransactionsReceivedOKBodyAO1); err != nil {
		return err
	}
	o.Version = listTransactionsReceivedOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListTransactionsReceivedOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	listTransactionsReceivedOKBodyAO0, err := swag.WriteJSON(o.ListTransactionsReceivedOKBodyAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, listTransactionsReceivedOKBodyAO0)

	listTransactionsReceivedOKBodyAO1, err := swag.WriteJSON(o.Version)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, listTransactionsReceivedOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list transactions received o k body
func (o *ListTransactionsReceivedOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ListTransactionsReceivedOKBodyAllOf0
	if err := o.ListTransactionsReceivedOKBodyAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with model.Version
	if err := o.Version.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *ListTransactionsReceivedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListTransactionsReceivedOKBody) UnmarshalBinary(b []byte) error {
	var res ListTransactionsReceivedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ListTransactionsReceivedOKBodyAllOf0 list transactions received o k body all of0
// swagger:model ListTransactionsReceivedOKBodyAllOf0
type ListTransactionsReceivedOKBodyAllOf0 []*model.Transaction

// Validate validates this list transactions received o k body all of0
func (o ListTransactionsReceivedOKBodyAllOf0) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(o); i++ {
		if swag.IsZero(o[i]) { // not required
			continue
		}

		if o[i] != nil {
			if err := o[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
