// Code generated by go-swagger; DO NOT EDIT.

/*
Package server Transaction
This is the Transaction Microservice, an immutable append-only Transaction Log in Modern Bank.


    Schemes:
      http
    Host: transactions
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package server
