// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/tetrateio/training/samples/modernbank/microservices/user/pkg/model"
)

// GetUserByUserNameReader is a Reader for the GetUserByUserName structure.
type GetUserByUserNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserByUserNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserByUserNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetUserByUserNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetUserByUserNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserByUserNameOK creates a GetUserByUserNameOK with default headers values
func NewGetUserByUserNameOK() *GetUserByUserNameOK {
	return &GetUserByUserNameOK{}
}

/*GetUserByUserNameOK handles this case with default header values.

Success!
*/
type GetUserByUserNameOK struct {
	Payload *model.User
}

func (o *GetUserByUserNameOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}][%d] getUserByUserNameOK  %+v", 200, o.Payload)
}

func (o *GetUserByUserNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByUserNameNotFound creates a GetUserByUserNameNotFound with default headers values
func NewGetUserByUserNameNotFound() *GetUserByUserNameNotFound {
	return &GetUserByUserNameNotFound{}
}

/*GetUserByUserNameNotFound handles this case with default header values.

User not found
*/
type GetUserByUserNameNotFound struct {
}

func (o *GetUserByUserNameNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{username}][%d] getUserByUserNameNotFound ", 404)
}

func (o *GetUserByUserNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserByUserNameInternalServerError creates a GetUserByUserNameInternalServerError with default headers values
func NewGetUserByUserNameInternalServerError() *GetUserByUserNameInternalServerError {
	return &GetUserByUserNameInternalServerError{}
}

/*GetUserByUserNameInternalServerError handles this case with default header values.

Internal server error
*/
type GetUserByUserNameInternalServerError struct {
}

func (o *GetUserByUserNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{username}][%d] getUserByUserNameInternalServerError ", 500)
}

func (o *GetUserByUserNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
