// tslint:disable
/**
 * Modern Bank
 * This is the API exposed to customers of Modern Bank.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Account,
    AccountFromJSON,
    AccountToJSON,
} from '../models';

export interface CreateAccountRequest {
    owner: string;
}

export interface DeleteAccountRequest {
    owner: string;
    number: number;
}

export interface GetAccountByNumberRequest {
    owner: string;
    number: number;
}

export interface ListAccountsRequest {
    owner: string;
}

/**
 * no description
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Creates a new account for a given customer
     * Create a new account for a customer
     */
    async createAccountRaw(requestParameters: CreateAccountRequest): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters.owner === null || requestParameters.owner === undefined) {
            throw new runtime.RequiredError('owner','Required parameter requestParameters.owner was null or undefined when calling createAccount.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{owner}/accounts`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters.owner))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Creates a new account for a given customer
     * Create a new account for a customer
     */
    async createAccount(requestParameters: CreateAccountRequest): Promise<Account> {
        const response = await this.createAccountRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete account by account number.
     * Delete account by account number
     */
    async deleteAccountRaw(requestParameters: DeleteAccountRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.owner === null || requestParameters.owner === undefined) {
            throw new runtime.RequiredError('owner','Required parameter requestParameters.owner was null or undefined when calling deleteAccount.');
        }

        if (requestParameters.number === null || requestParameters.number === undefined) {
            throw new runtime.RequiredError('number','Required parameter requestParameters.number was null or undefined when calling deleteAccount.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{owner}/accounts/{number}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters.owner))).replace(`{${"number"}}`, encodeURIComponent(String(requestParameters.number))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete account by account number.
     * Delete account by account number
     */
    async deleteAccount(requestParameters: DeleteAccountRequest): Promise<void> {
        await this.deleteAccountRaw(requestParameters);
    }

    /**
     * Get account details
     */
    async getAccountByNumberRaw(requestParameters: GetAccountByNumberRequest): Promise<runtime.ApiResponse<Account>> {
        if (requestParameters.owner === null || requestParameters.owner === undefined) {
            throw new runtime.RequiredError('owner','Required parameter requestParameters.owner was null or undefined when calling getAccountByNumber.');
        }

        if (requestParameters.number === null || requestParameters.number === undefined) {
            throw new runtime.RequiredError('number','Required parameter requestParameters.number was null or undefined when calling getAccountByNumber.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{owner}/accounts/{number}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters.owner))).replace(`{${"number"}}`, encodeURIComponent(String(requestParameters.number))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountFromJSON(jsonValue));
    }

    /**
     * Get account details
     */
    async getAccountByNumber(requestParameters: GetAccountByNumberRequest): Promise<Account> {
        const response = await this.getAccountByNumberRaw(requestParameters);
        return await response.value();
    }

    /**
     * Lists all accounts for a given customer
     * Lists all accounts for a given customer
     */
    async listAccountsRaw(requestParameters: ListAccountsRequest): Promise<runtime.ApiResponse<Array<Account>>> {
        if (requestParameters.owner === null || requestParameters.owner === undefined) {
            throw new runtime.RequiredError('owner','Required parameter requestParameters.owner was null or undefined when calling listAccounts.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{owner}/accounts`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters.owner))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountFromJSON));
    }

    /**
     * Lists all accounts for a given customer
     * Lists all accounts for a given customer
     */
    async listAccounts(requestParameters: ListAccountsRequest): Promise<Array<Account>> {
        const response = await this.listAccountsRaw(requestParameters);
        return await response.value();
    }

}
